version: '2'
services:
  solr:
    image: solr:6.6
    ports:
     - "4000:8983"
    volumes:
      - ./mydata:/opt/solr/server/mydata #Esure I could pass data to solr cores.
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
volumes:
  data: