version: '2'
services:
  solr:
    image: solr:6.6
    ports:
     - "4000:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
volumes:
  data: